### PR TITLE
Add Place and Poll support

### PR DESCRIPTION
**Pull request by ConnorSinnott**
Adds materialization support for the `Place` and `Poll` fields.

### CODE REVIEW

**Comment by ConnorSinnott** [comment]
Hey @DanielaSfregola, is there a way for me to see whats causing these circleci failures?

**Comment by DanielaSfregola** [comment]
> Hey @DanielaSfregola, is there a way for me to see whats causing these CircleCI failures?

https://app.circleci.com/pipelines/github/DanielaSfregola/twitter4s/28/workflows/10daaefe-ad76-471d-85b1-448232f9fb44/jobs/30

```
[info] Checking formatting for 272 Scala sources in root:compile ...
[error] /home/circleci/repo/src/main/scala/com/danielasfregola/twitter4s/entities/v2/Poll.scala has changes after scalafmt
[error] /home/circleci/repo/src/main/scala/com/danielasfregola/twitter4s/http/serializers/CustomFormats.scala has changes after scalafmt
[error] com.lucidchart.sbt.scalafmt.ScalafmtCheckFailure: 2 Scala sources not formatted in root:compile
```

To fix it, all you need to do is run "sbt test:compile" (ask sbt to compile the src code and the tests) and the files will be formatted correctly automatically

**Comment by ConnorSinnott** [comment]
Awesome! Got those corrected! Ready for your review now.

**Review by DanielaSfregola — APPROVED** [review]
Thanks @ConnorSinnott for your contribution!

LGTM

**Pull request merged**
