### PR TITLE
Remove gets from method call. Fixes #69.

### LINKED ISSUE #69: Remove `get` from methods calls
There are a lot of methods called `getProfileSettings`, `getUrl`, `getStatusesFilter` (this last one is terrible!).

As discussed during the ScalaXHack, this makes sense in java, but not in scala where we could have a much more natural method calls without the get: `profileSettings`, `url`, `filterStatuses`....

We should change all the methods to have the new style. Because this is a major change, we will have to:
- deprecate the old style methods to give time to people to migrate
- do a major release.

### PR DESCRIPTION
**Pull request by valydia**

### CODE REVIEW

**Comment by DanielaSfregola** [comment]
LOVING IT! ❤️  Thank you very much! 👯 

LGTM, but this will require a measure release so I'll wait to merge until we are ready to go -- Hopefully I will find the time to do it by the end of the year

**Comment by DanielaSfregola** [comment]
This resolves #69

**Comment by valydia** [comment]
Cool! Once the release is done I can remove the deprecated methods 👍

**Comment by DanielaSfregola** [comment]
I am doing the release right now 💃 
ETA: 15 minutes + 1h to be synced on maven central

**Comment by DanielaSfregola** [comment]
This is going to be released in version 3.0

**Pull request merged**
