### PR TITLE
Add twitter_volume as a field to be get by Trends by Location endpoint

### PR DESCRIPTION
**Pull request by carolinadominguez**
Twitter is providing twitter_volume field as part of the response when getting Trends by Location
See: https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place
I just have added the field to the Trends object to be parsed from the response.

### CODE REVIEW

**Comment by carolinadominguez** [comment]
Hi @DanielaSfregola thanks to you for your great API!
Do you plan to create a new version soon? It's a bit urgent for me to finish a release ;)

**Comment by DanielaSfregola** [comment]
Hi @carolinadominguez,
I'll try my best to do a release this weekend!

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
Released in twitter4s 5.4!

**Comment by carolinadominguez** [comment]
thank you so much! it's working fine for me :)

**Pull request merged**
