### PR TITLE
Adding support for Twitter's Streaming Public API

### PR DESCRIPTION
**Pull request by Geraz69**
Hello:

Here is my take on the task for adding Streaming support. Lets discuss if you see anything out of place or any design decision needs to be clarified. Big fan of your library BTW :D

Thanks.

### CODE REVIEW

**Comment by DanielaSfregola** [comment]
YES! Contributions! Amazing! 💃 

Thank you very much, this is really appreciated! I'll try to look into it as soon as possible :)

**Comment by DanielaSfregola** [comment]
Finally managed to have a look at it! 

Thank you @Geraz69, it's really good!

Overall LGTM, I'll like to do some really minor change by moving the case classes representing the responses in a separate package for consistency with the rest of the code -- no worries, I'll do it once I merge it.

In terms of design, I see you pass a generic actor that handles the received stream of messages.
This is fine, but rather than having a generic actor, I would have an twitter4s-specific abstract actor with some functions to implement to define the behaviour of each case. 

The advantages of this approach would be:
* people do not need to know that it is actually an actor, they can just define the behaviour of each case 
* we could provide some default implementations of this actor, so that the base case scenarios are covered.

I'll merge your PR and work on the changes on another branch.

Let me know your thoughts!

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
LGTM

**Comment by Geraz69** [comment]
It makes sense, thanks. I already covered my use case, I'll be playing around with the library and try to uncover any bug or performance issue. Looking forward for your changes and version 0.3 😄 

Thanks.

**Pull request merged**
