### PR TITLE
edit coordinates type to be able to get coordinates from client

### PR DESCRIPTION
**Pull request by lionetxue**
Hi Daniela,

I wasn't able to get coordinates using twitter4s streaming client.  I changed one line in your class Tweet and sbt publish-local to test.  It worked.
Thanks for the great work!

Lin

### CODE REVIEW

**Comment by DanielaSfregola** [comment]
Hi lionetxue, thank you very much for spotting and fixing the issue!

There is a test failure, so I cannot merge it yet -- I'll have a look at and merge it asap!

Cheers,
D.

**Comment by lionetxue** [comment]
Hi Daniela,

I think I might know why the test failed.  In tweet -> place -> GeoPlace, the Area is using coordinates class as well and I didn't change the coordinate type there.  

case class Area(coordinates: Seq[Seq[Seq[Double]]], `type`: String)

Lin

**Comment by bbarker** [comment]
`twitter/rest/search/tweets.json` has `coordinates` defined for tweet 658206491455807489 but `fixtures/rest/search/tweets.json` does not have it defined for the same tweet; pasting it in at line 1930 in the latter file will fix this:

```json
      "coordinates": {
        "type": "Point",
        "coordinates": [
          9.189618,
          45.466736
        ]
      },
```

Unfortunately, when I run `sbt test` in the master branch without this modification, I'm getting some other errors (so it would be good to know how to reproduce the test setup), but I think this should cover it.

**Comment by DanielaSfregola** [comment]
@lionetxue I finally managed to find the time to look at this issue! -- my apologies for the delay but I was on holiday for 2 weeks.

@bbarker is correct, the fixture in the test was simply no longer matching the data serialised by the client.

@bbarker I quite curious to know why the tests were failing for you. All you need to do to run the tests is:
- use java 8 for sbt
- run the command: `sbt test`
If you are able to replicate, It would be great if you could create an issue about it, so that I can look into it.
Also, thanks for the feedback, I'll add a section in the readme on how to contribute -- including how to run the tests.

**Comment by DanielaSfregola** [comment]
Closing this PR and continuing on #53 so that I can fix the broken test...

**Comment by DanielaSfregola** [comment]
FYI

This fix as now been release as part of 2.1-SNAPSHOT. 
I'll do my best and release a candidate within a few days -- no more holidays for me, so no more excuses! 💃 

Cheers,
D.

**Comment by lionetxue** [comment]
Thanks!  Good job, Daniela.

Lin

**Comment by DanielaSfregola** [comment]
This has now been released in version 2.1.

**Pull request closed without merging**
