### PR TITLE
Create TwitterSearchTweetsClient

### PR DESCRIPTION
**Pull request by ConnorSinnott**
**This PR has 3 commits:**
- Introduces a small utility that parses the query string into a Map of key, value pairs where the values are still url encoded. This allows us to confirm that a query parameter is encoded correctly without matching the entire query string and its multiple arguments.
- Marking more fields within `Error` as optional. Through testing it was revealed that some of these fields may be missing from responses.
- Added the new Tweet Search endpoint.

Just note that my test account is not elevated and is unable to use complex operators in the `/recent` search query, nor can I use the `/all` endpoint. So my testing was limited here.

### CODE REVIEW

**Comment by ConnorSinnott** [comment]
Hey @DanielaSfregola! This is almost ready to go. I'm wondering if its worth adding tests for this client? The SerDe between all these clients are the same and use the same "TweetResponse" fixture, so the only thing to really test here is that our `Parameter` objects are mapping correctly. Do you have any thoughts?

**Comment by DanielaSfregola** [comment]
Hi @ConnorSinnott , the tests are indeed testing something: that our parameter objects are mapping correctly, as you said :D 
So I'll be keen on having that part covered.

Cheers,
Daniela

**Comment by ConnorSinnott** [comment]
Hey @DanielaSfregola! I'm certainly in favor of keeping tests! My thinking is that this PR adds a "search" client which, as the other clients, would be tested in 2-ish parts:

The first part would be that all the parameters get mapped correctly e.g.:
```Scala
        .expectRequest { request =>
          request.method === HttpMethods.GET
          request.uri.endpoint === s"https://api.twitter.com/2/users/$userId/tweets"
          request.uri.rawQueryString === Some(Seq(
            V2SpecQueryHelper.buildTweetExpansions(expansions)
          ).mkString("&"))
        }
```
The second part is confirming that the response is deserialized correctly based on our mock fixtures:
```Scala
      result.rate_limit === rateLimit
      result.data === TweetsResponseFixture.fixture
```

Since every Twitter Tweet endpoint (tweetLookup, timelineLookup, tweetSearch) responds with a `TweetResponse` or `TweetsResponse` payload, each of the clients are re-testing that our `TweetResponse` fixtures get mapped to the expected model. To cut down on redundancy, I'm wondering if we should remove the fixture -> model validation from the client tests and instead bring them into their own tests.

**Comment by DanielaSfregola** [comment]
oh, I see...thanks for clarifying! Yes, I would be ok with that 👍

**Comment by ConnorSinnott** [comment]
Hey @DanielaSfregola. This is ready for review!

**Comment by DanielaSfregola** [comment]
@Mergifyio rebase

**Review by DanielaSfregola — APPROVED** [review]
Thanks @ConnorSinnott!

LGTM

**Pull request merged**
