### PR TITLE
JSON4S to 3.7.0-M7

### PR DESCRIPTION
**Pull request by zzvara**
Spark 3.1.0 requires JSON4S 3.7.0-M1+, this will come in handy.

### CODE REVIEW

**Comment by zzvara** [comment]
@DanielaSfregola could you publish a new version of this PR?

**Comment by DanielaSfregola** [comment]
Hi Zoltan, unfortunately we cannot update json4s to a milestone version: we need to rely on a stable version.

You still be able to force a version override if you need twitter4s to run with a specific version. Have you considered using a dependency override? see https://www.scala-sbt.org/1.x/docs/Library-Management.html#Overriding+a+version? (I am assuming you are using sbt).

Cheers,
D.

**Comment by zzvara** [comment]
@DanielaSfregola sure, but there is a binary incompatibility. Twitter4S is looking for JSON4S with version 3.6.X. Instead of shading, we decided to publish a snapshot.

As I noticed, 3.7.0-MX has been around for nearly a year (?) and a lot of projects depend on it, including Spark 3.1.0. We depend on it as well in production.

**Comment by DanielaSfregola** [comment]
Ok, that changes things! It they have been having milestone versions for 1y and spark depends on it, then I think it is safe enough to update.

**Review by DanielaSfregola — APPROVED** [review]
LGTM, even if this is a milestone version (see discussion on the PR)

**Comment by DanielaSfregola** [comment]
merged, I'll do my best to do a release during the weekend :)

**Comment by DanielaSfregola** [comment]
Ok, this took way more than I expected! I have released 7.1, it will be in maven central in a couple of hours!

Please, let me know if anything goes wrong - unfortunately Sonatype was having a bad day, so hopefully I didn't mess it up too much.

Cheers,
Daniela

**Pull request merged**
